baseURL = "https://coopmaths.fr/"
languageCode = "fr-fr"
title = "CoopMaths"
theme = "themecoop"
disablePathToLower = true #pour garder des URL en majuscule
publishDir = "../CoopMaths_Public" 

[params]
  description = "Exercices corrigés de Mathématiques pour une pédagogie coopérative et la personnalisation des apprentissages"

[blackfriday]
    fractions = false

[markup.goldmark.renderer]
  unsafe= true

#[permalinks]
#  "/" = "/:filename/"


### Pour un fonctionnement en local ###
#uglyurls = true
#relativeURLs = true

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
